# Generated by Django 5.2 on 2025-06-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0006_rename_issued_to_stktake_taken_by'),
        ('spp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysale',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='monthlysale',
            name='invoice_number',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysale',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='STK.stkstock'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('gpay', 'GPay'), ('paytm', 'Paytm'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='spp.monthlysale')),
            ],
        ),
    ]
