# Generated by Django 5.2 on 2025-06-04 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0002_remove_monthlysale_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
