# Generated by Django 5.2 on 2025-06-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company'),
        ('spp', '0003_alter_monthlysale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymententry',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmode'),
        ),
    ]
