# Generated by Django 5.2 on 2025-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0004_alter_paymententry_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymententry',
            name='payment_type',
            field=models.CharField(choices=[('gpay', 'GPay'), ('paytm', 'Paytm'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=50),
        ),
    ]
