# Generated by Django 5.2 on 2025-06-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_invoice'),
        ('spp', '0005_alter_paymententry_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysale',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
    ]
