# Generated by Django 5.2 on 2025-06-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_invoice'),
        ('spp', '0006_monthlysale_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
    ]
