# Generated by Django 5.2 on 2025-06-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_photo_id_type'),
        ('spp', '0007_monthlyexpense_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spp.monthlyexpense')),
            ],
        ),
    ]
