# Generated by Django 5.2 on 2025-06-05 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0008_monthlyexpense_employee_salarydeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
