# Generated by Django 5.2 on 2025-06-05 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0009_alter_monthlyexpense_date'),
        ('supplier', '0002_supplier_company_supplier_gst_number_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyvendorpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlyvendorpayment',
            name='vendor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
