# Generated by Django 5.2 on 2025-06-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company'),
        ('spp', '0010_alter_monthlyvendorpayment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyvendorpayment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='monthlyvendorpayment',
            name='total_payments',
        ),
        migrations.CreateModel(
            name='VendorPaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmode')),
                ('vendor_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='spp.monthlyvendorpayment')),
            ],
        ),
    ]
