# Generated by Django 5.2 on 2025-06-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0012_monthlyvendorpayment_total_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyvendorpayment',
            name='total_payments',
        ),
    ]
