# Generated by Django 5.2 on 2025-06-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0013_remove_monthlyvendorpayment_total_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyvendorpayment',
            name='total_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
