# Generated by Django 5.2 on 2025-06-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0014_monthlyvendorpayment_total_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyvendorpayment',
            name='total_payments',
        ),
    ]
