# Generated by Django 5.2 on 2025-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0015_remove_monthlyvendorpayment_total_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymententry',
            name='payment_type',
            field=models.CharField(choices=[('gpay', 'GPay'), ('paytm', 'Paytm'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=80),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='payment_mode',
            field=models.CharField(max_length=80),
        ),
    ]
