# Generated by Django 5.2 on 2025-06-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0016_alter_paymententry_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='amount_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
