# Generated by Django 5.2 on 2025-07-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0006_rename_issued_to_stktake_taken_by'),
        ('dashboard', '0002_company_invoice'),
        ('spp', '0017_monthlyexpense_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
        ),
        migrations.AlterField(
            model_name='monthlysale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='STK.stkstock'),
        ),
    ]
