# Generated by Django 5.2 on 2025-07-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0018_alter_monthlysale_company_alter_monthlysale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
