# Generated by Django 5.2 on 2025-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spp', '0019_alter_monthlysale_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=80),
        ),
        migrations.AlterField(
            model_name='monthlysale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysale',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=120),
        ),
    ]
