# Generated by Django 5.2 on 2025-07-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company_invoice'),
        ('spp', '0020_alter_monthlysale_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
        ),
    ]
