# Generated by Django 5.2 on 2025-06-02 09:28

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_id_file',
            field=models.FileField(blank=True, null=True, upload_to='employee_id_docs/', validators=[employees.models.validate_file_size]),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo_id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter', 'Voter ID'), ('passport', 'Passport'), ('license', 'Driving License')], max_length=20, null=True),
        ),
    ]
