# Generated by Django 5.2 on 2025-06-02 09:31

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_photo_id_file_employee_photo_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', validators=[employees.models.validate_file_size]),
        ),
    ]
