# Generated by Django 5.2 on 2025-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo_id_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
