# Generated by Django 5.2 on 2025-07-22 12:28

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_email_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee_photos/default.png', null=True, upload_to='employee_photos/', validators=[employees.models.validate_file_size]),
        ),
    ]
