# Generated by Django 5.2 on 2025-07-25 06:49

import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='employee_photos/user.png', null=True, upload_to='employee_photos/', validators=[employees.models.validate_file_size]),
        ),
    ]
