# Generated by Django 5.2 on 2025-06-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpPaymentType',
        ),
    ]
