# Generated by Django 5.2 on 2025-06-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permission_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
