# Generated by Django 5.2 on 2025-06-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_emppaymenttype'),
        ('manage_cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='entry_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrytype'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmode'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.segment'),
        ),
    ]
