# Generated by Django 5.2 on 2025-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_cashbook', '0002_alter_cashbookentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='entry_type',
            field=models.CharField(max_length=80),
        ),
    ]
