# Generated by Django 5.2 on 2025-07-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_amounttype'),
        ('manage_cashbook', '0003_alter_cashbookentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookentry',
            name='entry_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paymentmode'),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.segment'),
        ),
    ]
