# Generated by Django 5.2 on 2025-06-04 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STKStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(default='System', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='STK.stkstock')),
            ],
        ),
    ]
