# Generated by Django 5.2 on 2025-06-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0003_alter_stktake_taken_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stktake',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
    ]
