# Generated by Django 5.2 on 2025-06-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0004_stktake_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stktake',
            old_name='taken_by',
            new_name='issued_to',
        ),
    ]
