# Generated by Django 5.2 on 2025-06-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STK', '0005_rename_taken_by_stktake_issued_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stktake',
            old_name='issued_to',
            new_name='taken_by',
        ),
    ]
