# Generated by Django 5.2 on 2025-06-13 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_userpermission_permission_and_more'),
        ('customer', '0003_customer_latitude_customer_longitude'),
        ('employees', '0005_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('task_detail', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_tasks.servicecharge')),
            ],
        ),
        migrations.CreateModel(
            name='TaskBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmode')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='manage_tasks.task')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TaskServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_tasks.servicecharge')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_charges', to='manage_tasks.task')),
            ],
        ),
    ]
