# Generated by Django 5.2 on 2025-06-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
