# Generated by Django 5.2 on 2025-06-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='in_progress', max_length=80),
        ),
    ]
