# Generated by Django 5.2 on 2025-06-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0005_externalexpense_manualitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbilling',
            name='final_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
