# Generated by Django 5.2 on 2025-06-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0006_alter_taskbilling_final_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbilling',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
