# Generated by Django 5.2 on 2025-06-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tasks', '0007_alter_taskbilling_final_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoWorkerCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_charges', to='manage_tasks.task')),
            ],
        ),
    ]
