# Generated by Django 5.2 on 2025-07-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_phone'),
        ('dashboard', '0003_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_created', to='customer.customer'),
        ),
    ]
