# Generated by Django 5.2 on 2025-06-06 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0002_initial'),
        ('core', '0003_company'),
        ('employees', '0005_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepayment',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='employeepayment',
            name='user',
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='payment_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.paymentmode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employeepaymenttype'),
        ),
    ]
