# Generated by Django 5.2 on 2025-06-07 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_remove_employeepayment_bank_and_more'),
        ('core', '0004_delete_emppaymenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='approval_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='employee_payments', to='core.taskstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
