# Generated by Django 5.2 on 2025-06-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0002_initial'),
        ('customer', '0001_initial'),
        ('projects', '0002_project_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfollowup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='paymentfollowup',
            name='job_completed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
