# Generated by Django 5.2 on 2025-07-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIM', '0003_alter_paymentfollowup_customer_and_more'),
        ('customer', '0004_alter_customer_phone'),
        ('projects', '0003_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfollowup',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='paymentfollowup',
            name='job_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
